'use strict';

const crypto = require('crypto');
const zlib = require('zlib');
const { writeTar } = require('./tar');
const { gzipMembers, readApk, verifyApk } = require('./apk');

const file = (name, data, mode = 0o644) => ({ name, type: 'file', mode, data: Buffer.from(data) });

/** An apk v2 package: signature, control and data segments, each its own gzip member. */
function fixtureApk({ corruptData = false } = {}) {
  const data = zlib.gzipSync(
    writeTar([
      { name: 'usr', type: 'dir', mode: 0o755 },
      { name: 'usr/lib', type: 'dir', mode: 0o755 },
      file('usr/lib/xt_DSCP.ko', 'upper'),
      file('usr/lib/xt_dscp.ko', 'lower'),
      { name: 'usr/lib/libx.so', type: 'symlink', mode: 0o777, linkname: 'libx.so.1' },
    ]),
  );
  const datahash = crypto.createHash('sha256').update(data).digest('hex');
  const pkginfo = `# Generated by abuild\npkgname = fixture\npkgver = 1.0-r0\nlicense = MIT\ncommit = abc123\ndatahash = ${datahash}\n`;
  // The control and signature segments are tars without end blocks.
  const control = zlib.gzipSync(writeTar([file('.PKGINFO', pkginfo)]).subarray(0, 1024));
  const signature = zlib.gzipSync(writeTar([file('.SIGN.RSA.key.rsa.pub', 'sig')]).subarray(0, 1024));
  const finalData = corruptData ? zlib.gzipSync(writeTar([file('evil', 'x')])) : data;
  return {
    apk: Buffer.concat([signature, control, finalData]),
    controlChecksum: 'Q1' + crypto.createHash('sha1').update(control).digest('base64'),
  };
}

describe('gzipMembers', () => {
  it('splits concatenated gzip members at their exact boundaries', () => {
    const a = zlib.gzipSync(Buffer.from('one'));
    const b = zlib.gzipSync(Buffer.from('two'));
    const members = gzipMembers(Buffer.concat([a, b]));
    expect(members.map((m) => m.data.toString())).toEqual(['one', 'two']);
    expect(members[0].raw.equals(a)).toBe(true);
    expect(members[1].raw.equals(b)).toBe(true);
  });

  it('rejects trailing bytes that are not a gzip member, and a bad CRC', () => {
    const a = zlib.gzipSync(Buffer.from('one'));
    expect(() => gzipMembers(Buffer.concat([a, Buffer.from('junk')]))).toThrow(/gzip/);
    const bad = Buffer.from(a);
    bad[bad.length - 8] ^= 1;
    expect(() => gzipMembers(bad)).toThrow(/CRC/);
  });
});

describe('readApk', () => {
  it('yields only the data tar entries, and the control fields', () => {
    const { apk } = fixtureApk();
    const { entries, pkginfo } = readApk(apk);
    expect(entries.map((e) => e.name)).toEqual([
      'usr',
      'usr/lib',
      'usr/lib/libx.so',
      'usr/lib/xt_DSCP.ko',
      'usr/lib/xt_dscp.ko',
    ]);
    expect(pkginfo).toMatchObject({ pkgname: 'fixture', pkgver: '1.0-r0', license: 'MIT', commit: 'abc123' });
  });

  it('keeps both names that differ only in case, with their own contents', () => {
    const { entries } = readApk(fixtureApk().apk);
    const byName = Object.fromEntries(entries.map((e) => [e.name, e.data.toString()]));
    expect(byName['usr/lib/xt_DSCP.ko']).toBe('upper');
    expect(byName['usr/lib/xt_dscp.ko']).toBe('lower');
  });

  it('refuses a package that is not three gzip members', () => {
    expect(() => readApk(zlib.gzipSync(Buffer.from('x')))).toThrow(/segments/);
  });
});

describe('verifyApk', () => {
  it('accepts a package whose control segment and data hash match the index', () => {
    const { apk, controlChecksum } = fixtureApk();
    expect(() => verifyApk(apk, controlChecksum)).not.toThrow();
  });

  it('refuses a control segment that does not match the index checksum', () => {
    const { apk } = fixtureApk();
    expect(() => verifyApk(apk, 'Q1' + Buffer.alloc(20).toString('base64'))).toThrow(/control/);
  });

  it('refuses a data segment that does not match the control datahash', () => {
    const { apk, controlChecksum } = fixtureApk({ corruptData: true });
    expect(() => verifyApk(apk, controlChecksum)).toThrow(/datahash/);
  });
});
